import { Titillium_Web } from "next/font/google";
import './globals.css';
import CustomFooter from "./components/CustomFooter";
import CustomNavbar from "./components/CustomNavbar";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import './buttons.css';
import './navbar.css';
import './dividers.css';

import './our-services/pricing.css';


const titilliumWeb = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={titilliumWeb.className}>
        <CustomNavbar />
        <main>{children}</main>
        <CustomFooter />
      </body>
    </html>
  );
}
