import { Titillium_Web } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"
import './globals.css';
import CustomFooter from "./components/CustomFooter";
import CustomNavbar from "./components/CustomNavbar";
import Script from 'next/script';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import './buttons.css';
import './navbar.css';
import './dividers.css';
import './contact.css';

import './our-services/pricing.css';


const titilliumWeb = Titillium_Web({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-16744537812"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'AW-16744537812');
          `}
        </Script>
      </head>
      <body className={titilliumWeb.className}>
        <Analytics />
        <CustomNavbar />
        <main>{children}</main>
        <CustomFooter />
      </body>
    </html>
  );
}
